product-detail-page/.gitignore

i edited the ignore file

---

package-lock.json
product-detail-page/src/components/App.jsx

i added divs around the elements

edited the app component

---

product-detail-page/client/dist/stylesheet.css
product-detail-page/client/src/components/App.jsx
product-detail-page/client/src/components/ratingsAndReviews/Ratings.jsx
product-detail-page/client/src/components/ratingsAndReviews/Reviews.jsx
product-detail-page/client/src/components/ratingsAndReviews/ReviewsSummary.jsx

This new component takes in hard-coded reviews metadata as a prop from the Reviews component.
This PR includes a few changes:
1. Renames my components to follow the convention of API ("Reviews" instead of "Ratings")
2. Adds a stylesheet with just one style for now. This puts my summary component side-by-side with the reviews list.
3. Creates the ReviewSummary component
4. which includes a method to calculateStars (i.e., this product has 3.5 stars)
**I still need to write a test for calculateStars but I've confirmed it works as expected in the console. I will add this test to my backlog.**

create a basic Review Summary component

---

product-detail-page/client/dist/stylesheet.css
product-detail-page/client/src/components/relatedItems/productCard.jsx
product-detail-page/client/src/components/relatedItems/productList.jsx
product-detail-page/client/src/components/relatedItems/relatedButton.jsx
product-detail-page/client/src/components/relatedItems/relatedItems.jsx

This feature branch contains the barebones code to display all the necessary elements of the compare elements widget. 
It also contains basic css styling to display elements in a manner that primitively represents what the final product will be.

Boilerplate code and basic styling added for compare widget.

---

product-detail-page/client/src/components/ratingsAndReviews/Reviews.jsx
product-detail-page/client/src/components/ratingsAndReviews/ReviewsSummary.jsx

Updating main branch with changes from last week

ratings and review summary

---

product-detail-page/client/src/components/relatedItems/relatedItems.jsx

Fixed issue with variable in overview.

Comparisons boilerplate and comments

---

product-detail-page/client/dist/stylesheet.css
product-detail-page/client/src/components/ratingsAndReviews/BarGraph.jsx
product-detail-page/client/src/components/ratingsAndReviews/ReviewsList.jsx
product-detail-page/client/src/components/ratingsAndReviews/ReviewsSummary.jsx
product-detail-page/client/src/components/ratingsAndReviews/StarBar.jsx

This PR builds out the bar graph for each star in the Reviews summary component. The bar for 1 star, for example, shows what percentage of total raters gave the product 1 star.
It also adds a key for each review in the list to keep React happy.
Thanks for reviewing!

Star bar graph component

---

product-detail-page/client/src/components/ratingsAndReviews/BarGraph.jsx

I renamed one of my React components but did not change what I was exporting from that file

One line quick fix: export correct function from BarGraph.jsx

---

product-detail-page/client/dist/stylesheet.css

This PR should only change the stylesheet. Thanks!

fix styles for bar graph

---

product-detail-page/client/dist/stylesheet.css
product-detail-page/client/src/components/overview/StylesAndCart.jsx
product-detail-page/client/src/components/overview/StylesImage.jsx
product-detail-page/client/src/components/relatedItems/comparison.jsx
product-detail-page/client/src/components/relatedItems/productCard.jsx
product-detail-page/client/src/components/relatedItems/productList.jsx
product-detail-page/client/src/components/relatedItems/relatedItems.jsx
product-detail-page/client/src/lib/calculatePercentage.js
product-detail-page/package-lock.json
product-detail-page/package.json

With this PR the comparisons modal for related items is finished. 
It displays data dynamically for each item. There's still design to be taken care of. 
Another note in this pull request is that I added the underscore library as a general project dependency because of the need to map over objects.

Comparisons modal functionality finished.

---

product-detail-page/client/dist/stylesheet.css
product-detail-page/client/src/components/ratingsAndReviews/Review.jsx
product-detail-page/client/src/components/ratingsAndReviews/ReviewPhoto.jsx
product-detail-page/client/src/components/ratingsAndReviews/ReviewPhotos.jsx
product-detail-page/client/src/components/ratingsAndReviews/ReviewsList.jsx
product-detail-page/client/src/components/ratingsAndReviews/ReviewsModal.jsx
product-detail-page/client/src/components/ratingsAndReviews/ReviewsSummary.jsx
product-detail-page/client/src/components/ratingsAndReviews/Scale.jsx
product-detail-page/server/server.js

This PR improves the features and functionality of the review card by adding images and a modal to display images in full screen. To achieve this, it splits the photo-related section into multiple components -- ReviewPhoto, ReviewPhotos, and ReviewsModal.
It also builds out the scale component on the left.
Thanks for reviewing this one, and let me know if you want to talk more about the modal implementation! I will also share the react.dev link that I used as guidance once I find it again.

Review card updates

---

product-detail-page/client/src/components/relatedItems/deleteButton.jsx
product-detail-page/client/src/components/relatedItems/outfitList.jsx
product-detail-page/client/src/components/relatedItems/productCard.jsx
product-detail-page/client/src/components/relatedItems/productList.jsx
product-detail-page/client/src/components/relatedItems/relatedItems.jsx
product-detail-page/client/src/index.jsx

With this pull request I have refactored the initial useEffect calls on my main component to fit the Promise.all() system. 
It now performs only the bare minimum operations and API calls. 
With this update I have also included new functionality for the 'Your Outfit' component. Cards in this component now have the ability to be removed from the list.

Promise style & outfit behavior.

---

product-detail-page/client/dist/stylesheet.css
product-detail-page/client/src/components/questionsAndAnswers/AddAnswerModal.jsx
product-detail-page/client/src/components/questionsAndAnswers/AddQuestionModal.jsx
product-detail-page/client/src/components/questionsAndAnswers/AnswerEntry.jsx
product-detail-page/client/src/components/questionsAndAnswers/QuestionEntry.jsx
product-detail-page/client/src/components/questionsAndAnswers/QuestionList.jsx
product-detail-page/client/src/components/questionsAndAnswers/QuestionsAndAnswers.jsx
product-detail-page/client/src/components/questionsAndAnswers/Searchbar.jsx
product-detail-page/client/src/components/questionsAndAnswers/controllerQ&A.js
product-detail-page/server/controller.js
product-detail-page/server/server.js

This pull request contains many changes.  Dummy data has been replaced with data from the server/api calls.  Also, inline styling has been moved to the shared stylesheet.

New branch

---

product-detail-page/client/dist/stylesheet.css
product-detail-page/client/src/components/ratingsAndReviews/AddReview.jsx
product-detail-page/client/src/components/ratingsAndReviews/ReviewPhoto.jsx
product-detail-page/client/src/components/ratingsAndReviews/Reviews.jsx
product-detail-page/client/src/components/ratingsAndReviews/ReviewsList.jsx

This PR mainly builds out the form for adding a review. It doesn't yet submit anything, though. Thanks for reviewing this!

Add review form

---

product-detail-page/client/src/components/App.jsx
product-detail-page/client/src/components/ratingsAndReviews/Reviews.jsx

Thanks for reviewing this one! It's not an urgent change.

add states for productID and productInfo in the app-level component

---

product-detail-page/client/dist/index.html
product-detail-page/client/dist/stylesheet.css
product-detail-page/client/src/components/App.jsx
product-detail-page/client/src/components/overview/Overview.jsx

This PR introduces a title bar to the App component. The content is in App and the styles are at the bottom of the main stylesheet.
I also removed the title from index.html and the site-wide announcement from Overview. Thanks!

Create title bar

---

product-detail-page/client/dist/stylesheet.css

This PR adds some styling for the reviews section. Thanks!

Update styling for reviews

---

product-detail-page/client/dist/stylesheet.css
product-detail-page/client/src/components/App.jsx
product-detail-page/client/src/components/ratingsAndReviews/ReviewsList.jsx

This should only affect visual design. Thanks!

Update title bar and add spacing next to review sortBy selector

---

product-detail-page/client/src/components/App.jsx
product-detail-page/client/src/components/ratingsAndReviews/controllerReviews.js

Also, combine useEffects in App component into one. Previously we were fetching the product details twice in two separate useEffects.
Thanks for reviewing this one. The reviews section should update dynamically now!

Fix getReviews and getReviewsMetaData handlers

---

product-detail-page/client/dist/stylesheet.css

fix width for questions and answers & ratings and reviews components
